# Generated by Django 2.1.7 on 2019-05-10 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistinator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
