# Generated by Django 2.1.7 on 2019-04-12 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("logistinator", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="matching", name="end_datetime"),
        migrations.RemoveField(model_name="matching", name="room_id"),
        migrations.RemoveField(model_name="matching", name="start_datetime"),
        migrations.RemoveField(model_name="matching", name="weekly"),
    ]
