# Generated by Django 2.1.7 on 2019-04-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("logistinator", "0002_auto_20190411_1911")]

    operations = [
        migrations.AddField(
            model_name="matching",
            name="room_id",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cory-144MB", "Cory-144MB"),
                    ("Cory-258", "Cory-258"),
                    ("Cory-258", "Cory-258"),
                    ("Cory-400", "Cory-400"),
                    ("Cory-504", "Cory-504"),
                    ("Cory-521", "Cory-521"),
                    ("Cory-531", "Cory-531"),
                    ("Cory-540AB", "Cory-540AB"),
                    ("Cory-557", "Cory-557"),
                    ("Cory-Classroom-293", "Cory-Classroom-293"),
                    ("Cory-Classroom-299", "Cory-Classroom-299"),
                    ("Soda-306", "Soda-306"),
                    ("Soda-310", "Soda-310"),
                    ("Soda-320", "Soda-320"),
                    ("Soda-373", "Soda-373"),
                    ("Soda-380", "Soda-380"),
                    ("Soda-405", "Soda-405"),
                    ("Soda-430-438", "Soda-430-438"),
                    ("Soda-511", "Soda-511"),
                    ("Soda-606", "Soda-606"),
                    ("Soda-Alcove-283E", "Soda-Alcove-283E"),
                    ("Soda-Alcove-283H", "Soda-Alcove-283H"),
                    ("Soda-Alcove-341A", "Soda-Alcove-341A"),
                    ("Soda-Alcove-341B", "Soda-Alcove-341B"),
                    ("Soda-Alcove-411", "Soda-Alcove-411"),
                    ("Soda-Alcove-611", "Soda-Alcove-611"),
                ],
                max_length=16,
            ),
        )
    ]
