# Generated by Django 2.1.7 on 2019-04-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("logistinator", "0003_auto_20190418_1239")]

    operations = [
        migrations.RemoveField(model_name="availability", name="test"),
        migrations.RemoveField(model_name="imposedevent", name="bitstring"),
        migrations.RemoveField(model_name="imposedevent", name="user"),
        migrations.AlterField(
            model_name="imposedevent", name="active", field=models.BooleanField()
        ),
    ]
