# Generated by Django 2.1.7 on 2019-04-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("logistinator", "0003_matching_room_id")]

    operations = [
        migrations.AddField(
            model_name="matching",
            name="weekly",
            field=models.BooleanField(default=True),
        )
    ]
