# Generated by Django 2.1.7 on 2019-04-12 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("logistinator", "0005_auto_20190411_1921")]

    operations = [
        migrations.AlterField(
            model_name="matching",
            name="end_datetime",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="matching",
            name="start_datetime",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
