# Generated by Django 2.1.7 on 2019-04-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("logistinator", "0006_auto_20190411_1938")]

    operations = [
        migrations.AlterField(
            model_name="matching", name="room_id", field=models.CharField(max_length=16)
        )
    ]
