# Generated by Django 2.1.7 on 2019-04-12 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("logistinator", "0007_auto_20190411_1952")]

    operations = [
        migrations.AlterField(
            model_name="matching",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        )
    ]
