# Generated by Django 2.1.7 on 2019-04-19 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("logistinator", "0007_auto_20190411_1952")]

    operations = [
        migrations.CreateModel(
            name="Conflict",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("user_id", models.CharField(max_length=100)),
                ("room_id", models.CharField(max_length=16)),
                (
                    "start_datetime",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
            options={"abstract": False},
        )
    ]
