# Generated by Django 2.2.4 on 2019-09-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="permitted_absences",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
