# Generated by Django 2.1.3 on 2018-11-26 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='mentor',
            field=models.ForeignKey(limit_choices_to={'course': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Course'), 'role__in': ['JM', 'SM', 'CO']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_sections', to='scheduler.Profile'),
        ),
    ]
