# Generated by Django 2.1.5 on 2019-02-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20190127_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('ST', 'Student'), ('JM', 'Junior Mentor'), ('AM', 'Associate Mentor'), ('SM', 'Senior Mentor'), ('CO', 'Coordinator')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('section', 'week_start', 'attendee')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'default_spacetime')},
        ),
    ]
