# Generated by Django 2.2.4 on 2019-09-05 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0002_auto_20190904_1653"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="mentor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scheduler.Mentor",
            ),
        ),
    ]
