# Generated by Django 2.1.5 on 2019-04-07 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("scheduler", "0003_auto_20190207_0048")]

    operations = [
        migrations.RenameField(
            model_name="attendance", old_name="week_start", new_name="date"
        ),
        migrations.AlterUniqueTogether(
            name="attendance", unique_together={("date", "attendee")}
        ),
        migrations.RemoveField(model_name="attendance", name="section"),
    ]
