# Generated by Django 2.1.3 on 2018-11-26 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20181126_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='scheduler.Profile'),
        ),
    ]
