# Generated by Django 2.1.7 on 2019-03-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("scheduler", "0003_auto_20190207_0048")]

    operations = [
        migrations.CreateModel(
            name="Flag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("on", models.BooleanField(default=False)),
            ],
        )
    ]
