# Generated by Django 2.1.3 on 2018-11-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20181126_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='presence',
            field=models.CharField(blank=True, choices=[('PR', 'Present'), ('UN', 'Unexcused absence'), ('EX', 'Excused absence')], max_length=2),
        ),
    ]
