# Generated by Django 2.1.3 on 2019-01-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20181126_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.SlugField(max_length=100),
        ),
    ]
