# Generated by Django 2.2.4 on 2019-09-11 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0004_auto_20190904_2325_squashed_0005_coordinator_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="mentor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scheduler.Mentor",
            ),
        ),
    ]
