# Generated by Django 2.2.4 on 2019-09-15 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20190911_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='students', to='scheduler.Section'),
        ),
    ]
