# Generated by Django 2.1.3 on 2019-01-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20190105_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='scheduler.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['JM', 'SM', 'CO']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_sections', to='scheduler.Profile'),
        ),
    ]
