# Generated by Django 3.0.1 on 2020-01-06 05:40

from django.db import migrations, models
import scheduler.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_mentorbioinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorbioinfo',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='mentorbioinfo',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='mentorbioinfo',
            name='pfp',
            field=models.ImageField(upload_to=scheduler.models.bio_image_upload_path, verbose_name='Profile Picture'),
        ),
    ]
