# Generated by Django 3.0.1 on 2020-01-07 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import scheduler.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20200103_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorBioInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('biography', models.TextField()),
                ('pfp', models.ImageField(upload_to=scheduler.models.bio_image_upload_path, verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
