# Generated by Django 3.0.3 on 2020-02-20 01:40

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0008_auto_20200112_2051"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="section_start",
            field=models.DateField(
                default=datetime.datetime(
                    2020, 2, 20, 1, 40, 43, 642165, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
