# Generated by Django 3.0.3 on 2020-02-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_course_section_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='banned',
            field=models.BooleanField(
                default=False, help_text='A banned student cannot enroll in another section for the course they are banned from'),
        ),
    ]
