# Generated by Django 3.0.7 on 2020-09-06 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_auto_20200312_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacetime',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spacetimes', to='scheduler.Section'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='section',
            name='spacetime',
        ),
    ]
