# Generated by Django 3.0.7 on 2020-09-04 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_auto_20200312_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='spacetime_70',
            field=models.ForeignKey(help_text='A second recurring time and location for a section. This field is null for courses that only have one section per week.',
                                    null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_70', to='scheduler.Spacetime'),
        ),
        migrations.AlterField(
            model_name='section',
            name='spacetime',
            field=models.ForeignKey(help_text='The recurring time and location of a section. This can be temporarily overriden by the mentor, in which case the admin page will display the overriding times.',
                                    on_delete=django.db.models.deletion.CASCADE, related_name='section', to='scheduler.Spacetime'),
        ),
    ]
