# Generated by Django 3.0.7 on 2020-09-06 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0013_auto_20200906_1106"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spacetime",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spacetimes",
                to="scheduler.Section",
            ),
        ),
    ]
