# Generated by Django 3.0.7 on 2020-09-07 02:37

from django.db import migrations
import scheduler.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_auto_20200906_1147'),
    ]

    operations = [
        migrations.RunSQL(sql="CREATE TYPE day_of_week AS ENUM ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday');",
                          reverse_sql="DROP TYPE day_of_week;"),
        migrations.AlterField(
            model_name='spacetime',
            name='day_of_week',
            field=scheduler.models.DayOfWeekField(),
        ),
    ]
