# Generated by Django 3.0.7 on 2020-09-04 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_auto_20200903_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='spacetime_70',
        ),
        migrations.AddField(
            model_name='section',
            name='second_spacetime',
            field=models.ForeignKey(blank=True, help_text='A second recurring time and location for a section. This field is null for courses that only have one section per week.',
                                    null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_section', to='scheduler.Spacetime'),
        ),
    ]
