# Generated by Django 3.1.1 on 2020-09-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0016_auto_20200913_2112"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="coordinator",
            unique_together={("user", "course")},
        ),
    ]
