# Generated by Django 3.1.5 on 2021-08-03 03:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_auto_20200914_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ('sectionOccurrence',)},
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='scheduler_a_date_e76868_idx',
        ),
        migrations.AddField(
            model_name='sectionoccurrence',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.section'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sectionOccurrence',
            field=models.ForeignKey(default=django.utils.timezone.now,
                                    on_delete=django.db.models.deletion.CASCADE, to='scheduler.sectionoccurrence'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('sectionOccurrence', 'student')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
    ]
