# Generated by Django 3.2.6 on 2021-09-04 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_auto_20210802_2123'),
        ('scheduler', '0021_auto_20210812_1838'),
    ]

    operations = [
    ]
