# Generated by Django 3.2.6 on 2021-12-25 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0024_auto_20211123_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatcherSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.TextField()),
                ('num_mentors', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatcherPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.PositiveSmallIntegerField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.mentor')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.matcherslot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
