# Generated by Django 3.2.6 on 2021-12-25 06:10

from django.db import migrations
import django.db.models.deletion
import scheduler.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0025_matcherpreference_matcherslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='mentor',
            field=scheduler.models.OneToOneOrNoneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.mentor'),
        ),
    ]
