# Generated by Django 3.2.6 on 2022-02-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0026_user_priority_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionoccurrence',
            name='word_of_the_day',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
