# Generated by Django 3.2.6 on 2022-04-13 22:29

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0026_user_priority_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('sid', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-sid'],
            },
        ),
        migrations.AlterModelManagers(
            name='override',
            managers=[
                ('past_objects_included', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='spacetime',
            managers=[
                ('past_objects_included', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.semester'),
        ),
    ]
