# Generated by Django 3.2.6 on 2022-04-13 22:29

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


def initiate_semester(apps, schema_editor):
    Course = apps.get_model("scheduler", "Course")
    Semester = apps.get_model("scheduler", "Semester")
    initial_semester = Semester()
    initial_semester.save()
    for course in Course.objects.all():
        course.semester = initial_semester
        course.save()
    assert Course.objects.filter(semester__isnull=True).count() == 0


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0026_user_priority_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-sid'],
            },
        ),
        migrations.AlterModelManagers(
            name='override',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='spacetime',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.semester'),
        ),
        migrations.RunPython(
            initiate_semester, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='scheduler.semester'),
        ),
    ]
