# Generated by Django 3.2.6 on 2022-01-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0026_alter_section_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='matcher_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matcherslot',
            name='times',
            field=models.JSONField(),
        ),
    ]
