# Generated by Django 3.2.6 on 2022-02-09 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0026_user_priority_enrollment'),
        ('scheduler', '0027_auto_20220113_0349'),
    ]

    operations = [
    ]
