# Generated by Django 3.2.6 on 2022-06-10 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0027_auto_20220424_0333"),
        ("scheduler", "0027_link"),
    ]

    operations = []
