# Generated by Django 3.2.13 on 2022-08-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0029_auto_20220621_2235'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matcherslot',
            unique_together={('matcher', 'times')},
        ),
    ]
