# Generated by Django 3.2.6 on 2022-08-20 00:59

from django.db import migrations, models
import django.db.models.deletion

def copy_descriptions_to_label(apps, schema_editor):
    Course = apps.get_model("scheduler", "Course")
    Section = apps.get_model("scheduler", "Section")
    Label = apps.get_model("scheduler", "Label")
    for section in Section.objects.all():
        if section.description:
            label, created = Label.objects.get_or_create(
                name = section.description,
                showPopup = True,
                course = section.mentor.course
            )
            section.save()
            label.sections.add(section)
            label.save()

class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0029_section_description'),
    ]

    operations = [
        migrations.RunPython(copy_descriptions_to_label),
        migrations.RemoveField(
            model_name='section',
            name='description',
        ),
        migrations.AlterField(
            model_name='label',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='labels', to='scheduler.course'),
        ),
    ]
