# Generated by Django 3.2.6 on 2022-08-20 00:59

from django.db import migrations, models
import django.db.models.deletion

def copy_descriptions_to_label(apps, schema_editor):
    Course = apps.get_model("scheduler", "Section")
    Section = apps.get_model("scheduler", "Course")
    Label = apps.get_model("scheduler", "Label")
    for section in Section.objects.all():
        label = Label.objects.create(
            name = section.description,
            showPopup = True,
            course = section.mentor.course
        )
        section.save()

class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0029_section_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='description',
        ),
        migrations.RunPython(copy_descriptions_to_label),
        migrations.AlterField(
            model_name='label',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='labels', to='scheduler.course'),
        ),
    ]
