# Generated by Django 3.2.6 on 2022-09-20 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0030_alter_matcherslot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionoccurrence',
            name='spacetime',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scheduler.spacetime'),
            preserve_default=False,
        ),
    ]
