# Generated by Django 3.2.13 on 2022-10-04 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0030_alter_matcherslot_unique_together'),
        ('scheduler', '0030_auto_20220819_1759'),
    ]

    operations = [
    ]
