# Generated by Django 3.2.13 on 2022-09-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0030_auto_20220819_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='sections',
            field=models.ManyToManyField(blank=True, to='scheduler.Section'),
        ),
    ]
