# Generated by Django 3.2.15 on 2023-02-28 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0030_alter_matcherslot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='waitlist_capacity',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='WaitlistPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='waitlist_positions', to='scheduler.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
