# Generated by Django 3.2.16 on 2023-01-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0031_auto_20221115_2333"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="word_of_the_day_limit",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sectionoccurrence",
            name="word_of_the_day",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
