# Generated by Django 3.2.6 on 2022-09-27 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0030_alter_matcherslot_unique_together'),
        ('scheduler', '0031_alter_label_sections'),
    ]

    operations = [
    ]
