# Generated by Django 3.2.16 on 2023-02-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0032_word_of_the_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscribed",
            field=models.BooleanField(
                default=True, help_text="Automatically set to true when created"
            ),
        ),
    ]
