# Generated by Django 5.0.7 on 2025-02-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0032_word_of_the_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksheet",
            name="solution_schedule",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worksheet",
            name="worksheet_schedule",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
