# Generated by Django 4.2.7 on 2024-08-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0032_word_of_the_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="matcherslot",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
