# Generated by Django 4.2.7 on 2024-07-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0032_word_of_the_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="user",
            name="pronouns",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="pronunciation",
            field=models.CharField(default="", max_length=50),
        ),
    ]
