# Generated by Django 3.2.6 on 2022-09-27 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0032_merge_20220926_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='sections',
        ),
    ]
