# Generated by Django 3.2.15 on 2023-02-03 01:55

from django.db import migrations
import scheduler.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0032_word_of_the_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=scheduler.models.LowercaseEmailField(max_length=254, unique=True),
        ),
    ]
