# Generated by Django 5.0.7 on 2025-02-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0032_word_of_the_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffinitySectionTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Affinity tag for the section.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of what this affinity group represents.",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="section",
            name="description",
        ),
        migrations.AddField(
            model_name="section",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Affinity tags for the section.",
                to="scheduler.affinitysectiontag",
            ),
        ),
    ]
