# Generated by Django 4.2.1 on 2023-11-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0032_word_of_the_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="user",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="pronouns",
            field=models.CharField(
                blank=True,
                choices=[
                    ("he/him", "He"),
                    ("she/her", "She"),
                    ("they/them", "They"),
                    ("", "None"),
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pronunciation",
            field=models.CharField(default="", max_length=20),
        ),
    ]
