# Generated by Django 3.2.16 on 2023-04-11 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0032_word_of_the_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='receiver', to='scheduler.student')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='sender', to='scheduler.student')),
            ],
        ),
    ]
