# Generated by Django 5.0.7 on 2025-02-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0032_word_of_the_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="family",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
