# Generated by Django 4.2.7 on 2024-09-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0033_section_waitlist_capacity_waitlistedstudent"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="max_waitlist",
            field=models.SmallIntegerField(default=3),
        ),
    ]
