# Generated by Django 5.1.5 on 2025-09-05 11:37

import scheduler.models
import scheduler.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0033_user_bio_user_pronouns_user_pronunciation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                storage=scheduler.storage.ProfileImageStorage(),
                upload_to=scheduler.models.image_path,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="pronouns",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="pronunciation",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
