# Generated by Django 5.0.7 on 2025-09-03 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0033_matcherslot_description"),
        ("scheduler", "0033_mentor_family"),
    ]

    operations = []
