# Generated by Django 5.1.6 on 2025-10-27 23:02

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0033_matcherslot_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksheet",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 4, 25, 23, 2, 41, 748405, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="worksheet",
            name="solution_url",
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="worksheet",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 27, 23, 2, 41, 748396, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
