# Generated by Django 5.0.7 on 2025-02-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0033_affinitysectiontag_remove_section_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Affinity tags for the section.",
                null=True,
                to="scheduler.affinitysectiontag",
            ),
        ),
    ]
