# Generated by Django 5.1.6 on 2025-10-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0033_matcherslot_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="family",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
