# Generated by Django 5.1.6 on 2025-04-06 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0033_matcherslot_description"),
        ("scheduler", "0033_user_subscribed"),
    ]

    operations = []
