# Generated by Django 4.2.7 on 2024-10-16 21:42

from django.db import migrations, models

import csm_web.settings


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0033_user_bio_user_pronouns_user_pronunciation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, storage=csm_web.settings.ProfileImageStorage(), upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="user",
            name="pronouns",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="pronunciation",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
