# Generated by Django 3.2.15 on 2022-09-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0033_remove_label_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='sections',
            field=models.ManyToManyField(to='scheduler.Section'),
        ),
    ]
