# Generated by Django 5.0.7 on 2025-02-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0034_alter_section_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="tags",
        ),
        migrations.AddField(
            model_name="section",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="A brief note to add some extra information "
                + 'about the section, e.g. "EOP" or "early start".',
                max_length=100,
            ),
        ),
    ]
