# Generated by Django 5.1.6 on 2025-10-27 23:14

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0034_worksheet_end_time_worksheet_solution_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worksheet",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 4, 25, 23, 14, 19, 224273, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="worksheet",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
