# Generated by Django 4.2.7 on 2025-02-04 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0034_course_max_waitlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="max_waitlist",
        ),
        migrations.AlterField(
            model_name="waitlistedstudent",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waitlist",
                to="scheduler.section",
            ),
        ),
    ]
