# Generated by Django 4.2.7 on 2024-11-21 00:21

import scheduler.models
import scheduler.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0034_user_profile_image_alter_user_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                storage=scheduler.storage.ProfileImageStorage(),
                upload_to=scheduler.models.image_path,
            ),
        ),
    ]
