# Generated by Django 4.2.7 on 2024-11-18 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0034_course_max_waitlist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="waitlistedstudent",
            options={"ordering": ["position", "timestamp"]},
        ),
        migrations.RemoveField(
            model_name="course",
            name="max_waitlist",
        ),
        migrations.AddField(
            model_name="waitlistedstudent",
            name="position",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    "Manual position on the waitlist. Lower numbers have higher"
                    " priority."
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="waitlistedstudent",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waitlist",
                to="scheduler.section",
            ),
        ),
    ]
