# Generated by Django 5.1.6 on 2026-07-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scheduler",
            "0035_course_max_waitlist_enroll_section_waitlist_capacity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="calendar_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="section",
            name="calendar_event_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
