# Generated by Django 4.2.7 on 2024-11-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0035_alter_waitlistedstudent_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="max_waitlist",
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="waitlistedstudent",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="An inactive waitlisted student is a dropped student.",
            ),
        ),
    ]
