# Generated by Django 5.1.5 on 2025-02-01 09:13

from django.db import migrations, models


def forward_preferred_name(apps, _):
    """Creates default preferred name by saving objects (save function is overriden in model)"""
    User = apps.get_model("scheduler", "User")  # pylint: disable=invalid-name

    for user in User.objects.all():
        if not user.preferred_name:
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0035_alter_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(forward_preferred_name),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
    ]
