# Generated by Django 4.2.7 on 2024-11-25 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0036_course_max_waitlist_alter_waitlistedstudent_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="max_waitlist",
            new_name="waitlist_capacity",
        ),
        migrations.AlterField(
            model_name="waitlistedstudent",
            name="active",
            field=models.BooleanField(
                default=True, help_text="An inactive student is a dropped student."
            ),
        ),
        migrations.AlterField(
            model_name="waitlistedstudent",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waitlist_set",
                to="scheduler.section",
            ),
        ),
    ]
