# Generated by Django 4.2.7 on 2025-03-30 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0033_matcherslot_description"),
        ("scheduler", "0037_rename_max_waitlist_course_waitlist_capacity_and_more"),
    ]

    operations = []
