# Generated by Django 5.1.6 on 2025-04-07 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0034_merge_20250406_0056"),
        ("scheduler", "0038_merge_20250330_1353"),
    ]

    operations = []
