name: Django CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pytest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: csm_web_dev
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Parse Python version from runtime.txt
        run: |
          sed 's/[^0-9.]//g' runtime.txt | head > .python-version
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install Poetry
        run: |
          python3 -m venv /opt/poetry
          /opt/poetry/bin/pip install poetry
      - name: Install dependencies with Poetry
        run: |
          /opt/poetry/bin/poetry install --no-root --with=dev
      - name: Run Tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DJANGO_ENV: dev
          POSTGRES_PASSWORD: postgres
        run: |
          pytest csm_web
