name: pre-commit

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Parse Python version from runtime.txt
        run: |
          sed 's/[^0-9.]//g' runtime.txt | head > .python-version
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies with Poetry
        run: |
          poetry install --no-root --with=dev
          # add virtual environment to path for future steps
          echo .venv/bin >> $GITHUB_PATH
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0
